# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Balzabu
email: dbalzano@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  I always loved IT, I can't do anything about it!
baseurl: "/balzabu_blog" # the subpath of your site, e.g. /blog
url: "b4lz4bu.github.io" # the base hostname & protocol for your site
github_username:  b4lz4bu

# Build settings
markdown: kramdown
